services:
  app:
    build:
      context: .
      target: production
    expose:
      - "3000"

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - app
